config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/about', to: 'home#about'
  get '/contact', to: 'home#contact'

  resources :users do
    resources :scenarios
    resources :budgets
    resources :jobs
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
end

app/models/scenario.rb
class Scenario < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one_attached :main_image
  has_many :scenarios, dependent: :destroy
  has_many :jobs, dependent: :destroy
  has_many :budgets, dependent: :destroy
  
  validates :name, presence: true
  validates :email, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_user
  before_action :set_budget, except: [:index, :new, :create]
  
  def index
  end
  
  def new
    @budget = Budget.new
  end

  def create
    @budget = @user.budgets.create(budget_params)

    if @budget.save
      redirect_to user_budget_path(@user.id, @budget.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @budget.update(budget_params)
      redirect_to user_budget_path(@user.id, @budget.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @budget.destroy
    redirect_to user_path(@user.id), status: :see_other
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_budget
    @budget = @user.budgets.find(params[:id])
  end

  def budget_params
    params.require(:budget).permit(:title, :tithing_net, :rent, :food, :auto, :insurance, :child, :childcare, :entertainment, :travel, :clothing, :personal_care, :gifts, :misc_home, :other, :savings)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_user
  before_action :set_job, except: [:index, :new, :create]
  
  def index
  end
  
  def new
    @job = Job.new
  end

  def create
    @job = @user.jobs.create(job_params)

    if @job.save
      redirect_to user_job_path(@user.id, @job.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @job.update(job_params)
      redirect_to user_job_path(@user.id, @job.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @job.destroy
    redirect_to user_path(@user.id), status: :see_other
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_job
    @job = @user.jobs.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:title, :description, :state, :salary, :bonus, :salary_pct, :bonus_pct, :emp_spon_pct, :emp_match_pct, :health_pmt)
  end
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  before_action :set_user
  before_action :set_scenario, except: [:index, :new, :create]

  def index
  end

  def new
    @scenario = Scenario.new
  end

  def create
    @scenario = @user.scenarios.create(scenario_params)

    if @scenario.save
      redirect_to user_scenario_path(@user.id, @scenario.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @scenario.update(scenario_params)
      redirect_to user_scenario_path(@user.id, @scenario.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @scenario.destroy
    redirect_to user_path(@user.id), status: :see_other
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_scenario
    @scenario = @user.scenarios.find(params[:id])
  end

  def scenario_params
    params.require(:scenario).permit(:title, :description, :job, :goal, :budget)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: login_params[:email])
    if user && user.authenticate(login_params[:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      flash[:error] = "Sorry, we don't recognize that username/password."
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end

  private

  def login_params
    params.require(:login).permit(:email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end
  
  def edit
  end

  def update
    if @user.update(edit_user_params)
      redirect_to user_path(@user.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

  def edit_user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/budgets/edit.html.erb
<div class='form'>
  <%= form_with model: [@user, @budget] do |f| %>
    
    <div>
      <%=f.label :title, class: 'form-entry' %>
      <%=f.text_field :title, class: 'form-entry' %>
    </div>

    <div>
      <%=f.label :tithing_net, class: 'form-entry' %>
      <%=f.number_field :tithing_net, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :rent, class: 'form-entry' %>
      <%= f.number_field :rent, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :food, class: 'form-entry' %>
      <%= f.number_field :food, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :auto, class: 'form-entry' %>
      <%= f.number_field :auto, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :insurance, class: 'form-entry' %>
      <%= f.number_field :insurance, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :child, class: 'form-entry' %>
      <%= f.number_field :child, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :childcare, class: 'form-entry' %>
      <%= f.number_field :childcare, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :entertainment, class: 'form-entry' %>
      <%= f.number_field :entertainment, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :travel, class: 'form-entry' %>
      <%= f.number_field :travel, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :clothing, class: 'form-entry' %>
      <%= f.number_field :clothing, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :personal_care, class: 'form-entry' %>
      <%= f.number_field :personal_care, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :gifts, class: 'form-entry' %>
      <%= f.number_field :gifts, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :misc_home, class: 'form-entry' %>
      <%= f.number_field :misc_home, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :other, class: 'form-entry' %>
      <%= f.number_field :other, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :savings, class: 'form-entry' %>
      <%= f.number_field :savings, class: 'form-entry' %>
    </div>

    <div>
      <%= f.submit 'Update Budget', class: 'form-button' %>
    </div>

  <% end %>

  <br>
</div>

app/views/budgets/new.html.erb
<div class='form'>
  <%= form_with model: [@user, @user.budgets.build] do |f| %>
    
    <div>
      <%=f.label :title, class: 'form-entry' %>
      <%=f.text_field :title, class: 'form-entry' %>
    </div>

    <div>
      <%=f.label :tithing_net, class: 'form-entry' %>
      <%=f.number_field :tithing_net, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :rent, class: 'form-entry' %>
      <%= f.number_field :rent, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :food, class: 'form-entry' %>
      <%= f.number_field :food, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :auto, class: 'form-entry' %>
      <%= f.number_field :auto, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :insurance, class: 'form-entry' %>
      <%= f.number_field :insurance, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :child, class: 'form-entry' %>
      <%= f.number_field :child, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :childcare, class: 'form-entry' %>
      <%= f.number_field :childcare, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :entertainment, class: 'form-entry' %>
      <%= f.number_field :entertainment, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :travel, class: 'form-entry' %>
      <%= f.number_field :travel, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :clothing, class: 'form-entry' %>
      <%= f.number_field :clothing, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :personal_care, class: 'form-entry' %>
      <%= f.number_field :personal_care, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :gifts, class: 'form-entry' %>
      <%= f.number_field :gifts, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :misc_home, class: 'form-entry' %>
      <%= f.number_field :misc_home, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :other, class: 'form-entry' %>
      <%= f.number_field :other, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :savings, class: 'form-entry' %>
      <%= f.number_field :savings, class: 'form-entry' %>
    </div>

    <div>
      <%= f.submit 'Add Budget', class: 'form-button' %>
    </div>

  <% end %>

  <br>
</div>

app/views/budgets/show.html.erb
<div class='page'>
  <%= link_to 'Back', user_path(@user.id), class:'clickable' %>
  <br>
  <br>
  
  <p>Look it's a budget!</p>
  <br>

  <p>Title: <%= @budget.title %></p>
  <p>Tithing: <%= @budget.tithing_net %></p>
  <p>Rent: <%= @budget.rent %></p>
  <p>Food: <%= @budget.food %></p>
  <p>Travel: <%= @budget.travel %></p>
  <p>Savings: <%= @budget.savings %></p>
  <br>
  
  <%= link_to 'Edit Budget', edit_user_budget_path(@user.id), class:'clickable' %>
  <br>
  <%= link_to 'Delete Budget', user_budget_path(@user.id), method: :delete, class:'clickable' %>

</div>

app/views/home/about.html.erb
<div class='page'>
  <p>Create goals, set a budget, and see what's in your future.</p>
</div>

app/views/home/contact.html.erb
<div class='page'>
  <p>Call me, beep me, if you want to reach me</p>
</div>

app/views/home/index.html.erb
<div class='page'>
  <p> MyFi helps you plan for your financial future. </p>
</div>

app/views/jobs/edit.html.erb
<div class='form'>
  <%= form_with model: [@user, @job] do |f| %>
    
    <div>
      <%=f.label :title, class: 'form-entry' %>
      <%=f.text_field :title, class: 'form-entry' %>
    </div>

    <div>
      <%=f.label :description, class: 'form-entry' %>
      <%=f.text_field :description, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :state, class: 'form-entry' %>
      <%= f.text_field :state, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :salary, class: 'form-entry' %>
      <%= f.number_field :salary, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :bonus, class: 'form-entry' %>
      <%= f.number_field :bonus, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :salary_pct, class: 'form-entry' %>
      <%= f.number_field :salary_pct, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :bonus_pct, class: 'form-entry' %>
      <%= f.number_field :bonus_pct, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :emp_spon_pct, class: 'form-entry' %>
      <%= f.number_field :emp_spon_pct, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :emp_match_pct, class: 'form-entry' %>
      <%= f.number_field :emp_match_pct, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :health_pmt, class: 'form-entry' %>
      <%= f.number_field :health_pmt, class: 'form-entry' %>
    </div>

    <div>
      <%= f.submit 'Update Job', class: 'form-button' %>
    </div>

  <% end %>

  <br>
</div>

app/views/jobs/new.html.erb
<div class='form'>
  <%= form_with model: [@user, @user.jobs.build] do |f| %>
    
    <div>
      <%=f.label :title, class: 'form-entry' %>
      <%=f.text_field :title, class: 'form-entry' %>
    </div>

    <div>
      <%=f.label :description, class: 'form-entry' %>
      <%=f.text_field :description, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :state, class: 'form-entry' %>
      <%= f.text_field :state, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :salary, class: 'form-entry' %>
      <%= f.number_field :salary, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :bonus, class: 'form-entry' %>
      <%= f.number_field :bonus, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :salary_pct, class: 'form-entry' %>
      <%= f.number_field :salary_pct, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :bonus_pct, class: 'form-entry' %>
      <%= f.number_field :bonus_pct, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :emp_spon_pct, class: 'form-entry' %>
      <%= f.number_field :emp_spon_pct, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :emp_match_pct, class: 'form-entry' %>
      <%= f.number_field :emp_match_pct, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :health_pmt, class: 'form-entry' %>
      <%= f.number_field :health_pmt, class: 'form-entry' %>
    </div>

    <div>
      <%= f.submit 'Add Job', class: 'form-button' %>
    </div>

  <% end %>

  <br>
</div>

app/views/jobs/show.html.erb
<div class='page'>
  <%= link_to 'Back', user_path(@user.id), class:'clickable' %>
  <br>
  <br>
  
  <p>Look it's a job!</p>
  <br>

  <p>Title: <%= @job.title %></p>
  <p>Description: <%= @job.description %></p>
  <p>State: <%= @job.state %></p>
  <p>Salary: <%= @job.salary %></p>
  <p>Bonus: <%= @job.bonus %></p>
  <p>Annual Raise: <%= @job.salary_pct %></p>
  <br>
  
  <%= link_to 'Edit Job', edit_user_job_path(@user.id), class:'clickable' %>
  <br>
  <%= link_to 'Delete Job', user_job_path(@user.id), method: :delete, class:'clickable' %>

</div>

app/views/layouts/_alerts.html.erb
<div>
  <%= notice %>
</div>

app/views/layouts/_navbar.html.erb
<header>
  <div class="logo">
    <%= link_to 'MyFi', root_path %>
  </div>
  
  <nav>
    <ul class='nav-links'>
      <li><%= link_to 'About', about_path %></li>
      <li><%= link_to 'Contact', contact_path %></li>

      <% if current_user %>
        <li><%= link_to 'My Profile', user_path(current_user.id) %></li>
        <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Log In', login_path%></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myfi2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div>
      <br>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <br>
      <%= yield %>
    </div>
  </body>
</html>

app/views/scenarios/_form.html.erb
<div class='form'>
  <%= form_with model: [@user, @user.scenarios.build] do |f| %>
    
    <div>
      <%=f.label :title, class: 'form-entry' %>
      <%=f.text_field :title, class: 'form-entry' %>
    </div>

    <div>
      <%=f.label :description, class: 'form-entry' %>
      <%=f.text_field :description, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :job, class: 'form-entry' %>
      <%= f.text_field :job, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :goal, class: 'form-entry' %>
      <%= f.text_field :goal, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :budget, class: 'form-entry' %>
      <%= f.text_field :budget, class: 'form-entry' %>
    </div>

    <div>
      <%= f.submit 'Edit Scenario', class: 'form-button' %>
    </div>

  <% end %>

  <br>
</div>

app/views/scenarios/edit.html.erb
<div class='form'>
  <%= form_with model: [@user, @scenario] do |f| %>
    
    <div>
      <%=f.label :title, class: 'form-entry' %>
      <%=f.text_field :title, class: 'form-entry' %>
    </div>

    <div>
      <%=f.label :description, class: 'form-entry' %>
      <%=f.text_field :description, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :job, class: 'form-entry' %>
      <%= f.select :job, Job.all.pluck(:title), class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :goal, class: 'form-entry' %>
      <%= f.text_field :goal, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :budget, class: 'form-entry' %>
      <%= f.select :budget, Budget.all.pluck(:title), class: 'form-entry' %>
    </div>

    <div>
      <%= f.submit 'Edit Scenario', class: 'form-button' %>
    </div>

  <% end %>

  <br>
</div>

app/views/scenarios/new.html.erb
<div class='form'>
  <%= form_with model: [@user, @user.scenarios.build] do |f| %>
    
    <div>
      <%=f.label :title, class: 'form-entry' %>
      <%=f.text_field :title, class: 'form-entry' %>
    </div>

    <div>
      <%=f.label :description, class: 'form-entry' %>
      <%=f.text_field :description, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :job, class: 'form-entry' %>
      <%= f.text_field :job, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :goal, class: 'form-entry' %>
      <%= f.text_field :goal, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :budget, class: 'form-entry' %>
      <%= f.text_field :budget, class: 'form-entry' %>
    </div>

    <div>
      <%= f.submit 'Add Scenario', class: 'form-button' %>
    </div>

  <% end %>

  <br>
</div>

app/views/scenarios/show.html.erb
<div class='page'>
  <%= link_to 'Back', user_path(@user.id), class:'clickable' %>
  <br>
  <br>
  
  <p>Look it's a scenario!</p>
  <br>

  <p>Title: <%= @scenario.title %></p>
  <p>Description: <%= @scenario.description %></p>
  <p>Job: <%= @scenario.job %></p>
  <p>Goal: <%= @scenario.goal %></p>
  <p>Budget: <%= @scenario.budget %></p>
  <br>
  
  <%= link_to 'Edit Scenario', edit_user_scenario_path(@user.id), class:'clickable' %>
  <br>
  <%= link_to 'Delete Scenario', user_scenario_path(@user.id), method: :delete, class:'clickable' %>

</div>

app/views/users/edit.html.erb
<div class='form'>
  <%= form_with model: @user do |f| %>
    
    <div>
      <%=f.label :name, class: 'form-entry' %>
      <%=f.text_field :name, class: 'form-entry' %>
    </div>

    <div>
      <%=f.label :email, class: 'form-entry' %>
      <%=f.text_field :email, class: 'form-entry' %>
    </div>

    <div>
      <%= f.submit 'Update Profile', class: 'form-button' %>
    </div>

  <% end %>

  <br>
  <%= link_to "Don't want to make changes? Click here to return to the previous page.", user_path(current_user.id) %>
</div>

app/views/users/new.html.erb
<div class='form'>
  <%= form_with model: @user do |f| %>
    
    <div>
      <%=f.label :name, class: 'form-entry' %>
      <%=f.text_field :name, class: 'form-entry' %>
    </div>

    <div>
      <%=f.label :email, class: 'form-entry' %>
      <%=f.text_field :email, class: 'form-entry' %>
    </div>

    <div>
      <%= f.label :password, class: 'form-entry' %>
      <%= f.password_field :password, class: 'form-entry' %>
    </div>

    <div>
      <%= f.submit 'Sign Up', class: 'form-button' %>
    </div>

  <% end %>

  <br>
  <a class='page' href ='/login'>Already have an account? Click here to login</a>
</div>

app/views/users/show.html.erb
<div class='page'>
  <h1>Hi <%= @user.name %>!</h1>
  <br>

  <div>
    <p>My Jobs</p>
    <% @user.jobs.each do |job| %>
      <%= link_to job.title, user_job_path(@user, job), class:'clickable' %>
      <br>
    <% end %>
  </div>
  <br>

  <div>
    <p>My Budgets</p>
    <% @user.budgets.each do |budget| %>
      <%= link_to budget.title, user_budget_path(@user, budget), class:'clickable' %>
      <br>
    <% end %>
  </div>
  <br>

  <div>
    <p>My Scenarios</p>
    <% @user.scenarios.each do |scenario| %>
      <%= link_to scenario.title, user_scenario_path(@user, scenario), class:'clickable' %>
      <br>
    <% end %>
  </div>

  <p>Create Something New</p>
  <%= link_to 'Add Job', new_user_job_path(@user.id), class:'clickable' %>
  <br>
  <%= link_to 'Add Budget', new_user_budget_path(@user.id), class:'clickable' %>
  <br>
  <%= link_to 'Add Scenario', new_user_scenario_path(@user.id), class:'clickable' %>
  <br>
  <br>

  <p>Other Stuff</p>
  <%= link_to 'Update Profile', edit_user_path(@user.id), class:'clickable' %><br>
</div>